# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.project_svc:
        class: AppBundle\Service\ProjectService
        arguments: [@doctrine.orm.entity_manager]
    app.person_svc:
        class: AppBundle\Service\PersonService
        arguments: [@doctrine.orm.entity_manager]